require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Runs a Pry console"
  task :console do
    # This line turns on logging of the SQL generated by Active Record
    ActiveRecord::Base.logger = Logger.new(STDOUT)
    
    # Open a Pry session
    Pry.start
  end
desc "Runs a Artist.new with name: john"
  task :new_artist_with_save do
  a = Artist.new(name: "Jon")
  a.age = 30
  a.save 
  end